# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RefHead.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(321, 180)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.RefHeadtabWidget = QtWidgets.QTabWidget(Dialog)
        self.RefHeadtabWidget.setObjectName("RefHeadtabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 7, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.REVspinBox = QtWidgets.QSpinBox(self.frame)
        self.REVspinBox.setMaximum(200)
        self.REVspinBox.setObjectName("REVspinBox")
        self.gridLayout_2.addWidget(self.REVspinBox, 1, 5, 1, 1)
        self.RBTspinBox = QtWidgets.QSpinBox(self.frame)
        self.RBTspinBox.setMaximum(200)
        self.RBTspinBox.setObjectName("RBTspinBox")
        self.gridLayout_2.addWidget(self.RBTspinBox, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 6, 1, 1)
        self.RAPspinBox = QtWidgets.QSpinBox(self.frame)
        self.RAPspinBox.setMaximum(200)
        self.RAPspinBox.setObjectName("RAPspinBox")
        self.gridLayout_2.addWidget(self.RAPspinBox, 1, 8, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.SetButton = QtWidgets.QPushButton(self.tab)
        self.SetButton.setObjectName("SetButton")
        self.horizontalLayout_2.addWidget(self.SetButton)
        self.DefaultButton = QtWidgets.QPushButton(self.tab)
        self.DefaultButton.setObjectName("DefaultButton")
        self.horizontalLayout_2.addWidget(self.DefaultButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.RefHeadtabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.RefHeadtabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.RefHeadtabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "RAP:"))
        self.label.setText(_translate("Dialog", "RBT:"))
        self.label_4.setText(_translate("Dialog", "REV:"))
        self.SetButton.setText(_translate("Dialog", "Set"))
        self.DefaultButton.setText(_translate("Dialog", "Default"))
        self.RefHeadtabWidget.setTabText(self.RefHeadtabWidget.indexOf(self.tab), _translate("Dialog", "Refrence head indices"))
