# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(281, 99)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.UnLockButton = QtWidgets.QPushButton(self.frame)
        self.UnLockButton.setObjectName("UnLockButton")
        self.gridLayout_2.addWidget(self.UnLockButton, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.UnLocklineEdit = QtWidgets.QLineEdit(self.frame)
        self.UnLocklineEdit.setMinimumSize(QtCore.QSize(162, 20))
        self.UnLocklineEdit.setMaximumSize(QtCore.QSize(162, 20))
        self.UnLocklineEdit.setObjectName("UnLocklineEdit")
        self.gridLayout_2.addWidget(self.UnLocklineEdit, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.UnLockButton.setText(_translate("Form", "UnLock"))
        self.label.setText(_translate("Form", "Enter a numeric code to unlock:"))
